### ISSUE TITLE
CI release failure

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-amt-plugin#11]
https://circleci.com/gh/vapor-ware/synse-amt-plugin/34
CI fails to release if there are no previous tags. It fails around:
```
--since-tag $(git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`)
```
when generating the changelog

```
fatal: No tags can describe '1440ff41b8c09312dbc6be960257d357bb4b68d3'.
Try --always, or create some tags.
/usr/local/bundle/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/parser.rb:16:in `parse_options': missing argument: --since-tag (OptionParser::MissingArgument)
	from /usr/local/bundle/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator.rb:27:in `initialize'
	from /usr/local/bundle/gems/github_changelog_generator-1.14.3/bin/github_changelog_generator:5:in `new'
	from /usr/local/bundle/gems/github_changelog_generator-1.14.3/bin/github_changelog_generator:5:in `<top (required)>'
	from /usr/local/bundle/bin/github_changelog_generator:23:in `load'
	from /usr/local/bundle/bin/github_changelog_generator:23:in `<main>'
Exited with code 1
```

Didn't see this in the other repos because they already had tags!

**Comment by edaniszewski** [comment]
also, if drafting the release fails like this, should that prevent the release tags from being pushed to dockerhub?

any thoughts on this @timfallmk ?

**Comment by timfallmk** [comment]
This sounds like a borderline edge case, but we _could_ add a check for it.

More importantly, I think failure to generate a changelog should fail any release steps that are downstream, so it _should_ fail to push dockerhub tags. I could be totally wrong about that. If it doesn't and the tags exist there, I don't think it's too big a deal since it would be a nightmare to try and only push them at the end.
